server {
    listen 80;

    location = / {
        return 301 /daily_gratitude_journal/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /daily_gratitude_journal/index.html;
    }

    error_page 404 /daily_gratitude_journal/index.html;
}
